# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Dapper"; version = "2.0.143"; hash = "sha256-OSsfIBfDNuMh6SpA1DxNQdHRh+n4UVHNeF+RAl6qeGM="; })
  (fetchNuGet { pname = "LibGit2Sharp"; version = "0.27.2"; hash = "sha256-ImU5Viu1DA+HFiNVzx4Ftb6xzUnZyvqLZxEFrflSXVg="; })
  (fetchNuGet { pname = "LibGit2Sharp.NativeBinaries"; version = "2.0.320"; hash = "sha256-OqKtOLskLUdb1gldAdyQC2kcDL/r+RGOjkdyplTYTg0="; })
  (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "5.0.0"; hash = "sha256-LIcg1StDcQLPOABp4JRXIs837d7z0ia6+++3SF3jl1c="; })
  (fetchNuGet { pname = "Microsoft.Win32.Registry"; version = "5.0.0"; hash = "sha256-9kylPGfKZc58yFqNKa77stomcoNnMeERXozWJzDcUIA="; })
  (fetchNuGet { pname = "Mono.Unix"; version = "7.1.0-final.1.21458.1"; hash = "sha256-tm3niOm4OFCe/kL5M5zwCZgfHEaPtmDqsOLN6GExYHs="; })
  (fetchNuGet { pname = "MySqlConnector"; version = "2.2.6"; hash = "sha256-AKw+W62jeCm1sLo4hy6aON3ppfQDb89LCHLXvx0z5mE="; })
  (fetchNuGet { pname = "NLog"; version = "5.2.4"; hash = "sha256-XhMNSsVQY8c7txcNg+ZPTsqRVQkM+VLAC7UkJDonckI="; })
  (fetchNuGet { pname = "protobuf-net"; version = "3.2.30"; hash = "sha256-keRy5OWT+/tlZt3D7x+9PEdjTvEJcZdYsf/i1ZBtciE="; })
  (fetchNuGet { pname = "protobuf-net.Core"; version = "3.2.30"; hash = "sha256-GMpJNecoBfrV2VgpYOhcZnKZaLFDObNLcX2LBTThrwY="; })
  (fetchNuGet { pname = "SteamKit2"; version = "3.0.0-beta.2"; hash = "sha256-aQ1zMyWPOvGFcDYYscn/qTpnWS4HfK/k1NLk37zeVAE="; })
  (fetchNuGet { pname = "System.Collections.Immutable"; version = "7.0.0"; hash = "sha256-9an2wbxue2qrtugYES9awshQg+KfJqajhnhs45kQIdk="; })
  (fetchNuGet { pname = "System.CommandLine"; version = "2.0.0-beta4.22272.1"; hash = "sha256-zSO+CYnMH8deBHDI9DHhCPj79Ce3GOzHCyH1/TiHxcc="; })
  (fetchNuGet { pname = "System.IO.Hashing"; version = "8.0.0"; hash = "sha256-szOGt0TNBo6dEdC3gf6H+e9YW3Nw0woa6UnCGGGK5cE="; })
  (fetchNuGet { pname = "System.Security.AccessControl"; version = "5.0.0"; hash = "sha256-ueSG+Yn82evxyGBnE49N4D+ngODDXgornlBtQ3Omw54="; })
  (fetchNuGet { pname = "System.Security.Principal.Windows"; version = "5.0.0"; hash = "sha256-CBOQwl9veFkrKK2oU8JFFEiKIh/p+aJO+q9Tc2Q/89Y="; })
]
